"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-31 13:16:33.728120

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_symbol', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_canonical_symbol'), 'assets', ['canonical_symbol'], unique=True)
    op.create_table('service_health_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_health_events'))
    )
    op.create_index(op.f('ix_service_health_events_service_name'), 'service_health_events', ['service_name'], unique=False)
    op.create_table('strategy_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ui_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('defaults_by_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_market_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_definitions')),
    sa.UniqueConstraint('type_code', name=op.f('uq_strategy_definitions_type_code'))
    )
    op.create_table('technical_error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('execution_context_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_or_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_error_logs'))
    )
    op.create_index(op.f('ix_technical_error_logs_module'), 'technical_error_logs', ['module'], unique=False)
    op.create_index(op.f('ix_technical_error_logs_occurred_at'), 'technical_error_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_technical_error_logs_severity'), 'technical_error_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_technical_error_logs_user_id'), 'technical_error_logs', ['user_id'], unique=False)
    op.create_table('trading_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_providers')),
    sa.UniqueConstraint('code', name=op.f('uq_trading_providers_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('dashboard_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('agent_room_mode', sa.String(), nullable=False),
    sa.Column('widget_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_preferences'))
    )
    op.create_index(op.f('ix_dashboard_preferences_user_id'), 'dashboard_preferences', ['user_id'], unique=False)
    op.create_table('execution_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_execution_contexts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_contexts'))
    )
    op.create_index(op.f('ix_execution_contexts_user_id'), 'execution_contexts', ['user_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('encrypted_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('encryption_key_version', sa.Integer(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_channels_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_index(op.f('ix_notification_channels_user_id'), 'notification_channels', ['user_id'], unique=False)
    op.create_table('provider_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_asset_id', sa.String(length=255), nullable=False),
    sa.Column('provider_symbol', sa.String(length=50), nullable=False),
    sa.Column('tradable', sa.Boolean(), nullable=False),
    sa.Column('fractionable', sa.Boolean(), nullable=False),
    sa.Column('shortable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_provider_assets_asset_id_assets')),
    sa.ForeignKeyConstraint(['provider_id'], ['trading_providers.id'], name=op.f('fk_provider_assets_provider_id_trading_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_assets')),
    sa.UniqueConstraint('provider_id', 'provider_symbol', name='uq_provider_symbol')
    )
    op.create_index(op.f('ix_provider_assets_asset_id'), 'provider_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_provider_assets_provider_id'), 'provider_assets', ['provider_id'], unique=False)
    op.create_table('user_trading_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trading_provider_id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('encrypted_api_key', sa.String(), nullable=True),
    sa.Column('encrypted_secret_key', sa.String(), nullable=True),
    sa.Column('encryption_key_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['trading_provider_id'], ['trading_providers.id'], name=op.f('fk_user_trading_accounts_trading_provider_id_trading_providers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_trading_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_trading_accounts'))
    )
    op.create_index(op.f('ix_user_trading_accounts_trading_provider_id'), 'user_trading_accounts', ['trading_provider_id'], unique=False)
    op.create_index(op.f('ix_user_trading_accounts_user_id'), 'user_trading_accounts', ['user_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('conversation_thread_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_agent_messages_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index(op.f('ix_agent_messages_conversation_thread_id'), 'agent_messages', ['conversation_thread_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_execution_context_id'), 'agent_messages', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_user_id'), 'agent_messages', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_alerts_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_execution_context_id'), 'alerts', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_channel_id', sa.UUID(), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notification_channel_id'], ['notification_channels.id'], name=op.f('fk_notification_subscriptions_notification_channel_id_notification_channels')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_subscriptions'))
    )
    op.create_index(op.f('ix_notification_subscriptions_notification_channel_id'), 'notification_subscriptions', ['notification_channel_id'], unique=False)
    op.create_index(op.f('ix_notification_subscriptions_user_id'), 'notification_subscriptions', ['user_id'], unique=False)
    op.create_table('onboarding_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_trading_account_id', sa.UUID(), nullable=True),
    sa.Column('step_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_onboarding_steps_user_id_users')),
    sa.ForeignKeyConstraint(['user_trading_account_id'], ['user_trading_accounts.id'], name=op.f('fk_onboarding_steps_user_trading_account_id_user_trading_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_steps'))
    )
    op.create_index(op.f('ix_onboarding_steps_user_id'), 'onboarding_steps', ['user_id'], unique=False)
    op.create_index(op.f('ix_onboarding_steps_user_trading_account_id'), 'onboarding_steps', ['user_trading_account_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('daily_pl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_pl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw_provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_portfolio_snapshots_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolio_snapshots_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index(op.f('ix_portfolio_snapshots_execution_context_id'), 'portfolio_snapshots', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_snapshot_at'), 'portfolio_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_table('positions_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_positions_snapshots_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_positions_snapshots_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions_snapshots'))
    )
    op.create_index(op.f('ix_positions_snapshots_execution_context_id'), 'positions_snapshots', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_positions_snapshots_snapshot_at'), 'positions_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_positions_snapshots_symbol'), 'positions_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_snapshots_user_id'), 'positions_snapshots', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_definition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition_version', sa.String(length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_evaluation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_signal', sa.String(length=20), nullable=True),
    sa.Column('cloned_from_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['strategies.id'], name=op.f('fk_strategies_cloned_from_id_strategies')),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_strategies_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['strategy_definition_id'], ['strategy_definitions.id'], name=op.f('fk_strategies_strategy_definition_id_strategy_definitions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    op.create_index(op.f('ix_strategies_execution_context_id'), 'strategies', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_strategies_strategy_definition_id'), 'strategies', ['strategy_definition_id'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_data_timestamp', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_agent_decisions_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_agent_decisions_strategy_id_strategies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_decisions'))
    )
    op.create_index(op.f('ix_agent_decisions_correlation_id'), 'agent_decisions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_execution_context_id'), 'agent_decisions', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_strategy_id'), 'agent_decisions', ['strategy_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('notification_channel_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_notification_deliveries_alert_id_alerts')),
    sa.ForeignKeyConstraint(['notification_channel_id'], ['notification_channels.id'], name=op.f('fk_notification_deliveries_notification_channel_id_notification_channels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    op.create_index(op.f('ix_notification_deliveries_alert_id'), 'notification_deliveries', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_notification_channel_id'), 'notification_deliveries', ['notification_channel_id'], unique=False)
    op.create_table('strategy_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('window_key', sa.String(length=255), nullable=False),
    sa.Column('market_data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_strategy_runs_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_runs_strategy_id_strategies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_runs')),
    sa.UniqueConstraint('strategy_id', 'window_key', name='uq_strategy_runs_window')
    )
    op.create_index(op.f('ix_strategy_runs_execution_context_id'), 'strategy_runs', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_strategy_runs_strategy_id'), 'strategy_runs', ['strategy_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_decision_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_decision_id'], ['agent_decisions.id'], name=op.f('fk_risk_decisions_agent_decision_id_agent_decisions')),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_risk_decisions_execution_context_id_execution_contexts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_decisions'))
    )
    op.create_index(op.f('ix_risk_decisions_agent_decision_id'), 'risk_decisions', ['agent_decision_id'], unique=False)
    op.create_index(op.f('ix_risk_decisions_correlation_id'), 'risk_decisions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_risk_decisions_execution_context_id'), 'risk_decisions', ['execution_context_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('risk_decision_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('notional', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('time_in_force', sa.String(length=10), nullable=False),
    sa.Column('stop_loss', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('take_profit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('client_order_id', sa.String(length=255), nullable=False),
    sa.Column('provider_order_id', sa.String(length=255), nullable=True),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_orders_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['risk_decision_id'], ['risk_decisions.id'], name=op.f('fk_orders_risk_decision_id_risk_decisions')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_orders_strategy_id_strategies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_order_id'),
    sa.UniqueConstraint('execution_context_id', 'idempotency_key', name='uq_orders_idempotency')
    )
    op.create_index(op.f('ix_orders_correlation_id'), 'orders', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_orders_execution_context_id'), 'orders', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_orders_risk_decision_id'), 'orders', ['risk_decision_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execution_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], name=op.f('fk_order_events_execution_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index(op.f('ix_order_events_execution_context_id'), 'order_events', ['execution_context_id'], unique=False)
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_execution_context_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_risk_decision_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_execution_context_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_correlation_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_risk_decisions_execution_context_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_correlation_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_agent_decision_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_strategy_runs_strategy_id'), table_name='strategy_runs')
    op.drop_index(op.f('ix_strategy_runs_execution_context_id'), table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_index(op.f('ix_notification_deliveries_notification_channel_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_alert_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_agent_decisions_strategy_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_execution_context_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_correlation_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_strategy_definition_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_execution_context_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_positions_snapshots_user_id'), table_name='positions_snapshots')
    op.drop_index(op.f('ix_positions_snapshots_symbol'), table_name='positions_snapshots')
    op.drop_index(op.f('ix_positions_snapshots_snapshot_at'), table_name='positions_snapshots')
    op.drop_index(op.f('ix_positions_snapshots_execution_context_id'), table_name='positions_snapshots')
    op.drop_table('positions_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_snapshot_at'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_execution_context_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_onboarding_steps_user_trading_account_id'), table_name='onboarding_steps')
    op.drop_index(op.f('ix_onboarding_steps_user_id'), table_name='onboarding_steps')
    op.drop_table('onboarding_steps')
    op.drop_index(op.f('ix_notification_subscriptions_user_id'), table_name='notification_subscriptions')
    op.drop_index(op.f('ix_notification_subscriptions_notification_channel_id'), table_name='notification_subscriptions')
    op.drop_table('notification_subscriptions')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_execution_context_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_agent_messages_user_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_execution_context_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_conversation_thread_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_user_trading_accounts_user_id'), table_name='user_trading_accounts')
    op.drop_index(op.f('ix_user_trading_accounts_trading_provider_id'), table_name='user_trading_accounts')
    op.drop_table('user_trading_accounts')
    op.drop_index(op.f('ix_provider_assets_provider_id'), table_name='provider_assets')
    op.drop_index(op.f('ix_provider_assets_asset_id'), table_name='provider_assets')
    op.drop_table('provider_assets')
    op.drop_index(op.f('ix_notification_channels_user_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_execution_contexts_user_id'), table_name='execution_contexts')
    op.drop_table('execution_contexts')
    op.drop_index(op.f('ix_dashboard_preferences_user_id'), table_name='dashboard_preferences')
    op.drop_table('dashboard_preferences')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trading_providers')
    op.drop_index(op.f('ix_technical_error_logs_user_id'), table_name='technical_error_logs')
    op.drop_index(op.f('ix_technical_error_logs_severity'), table_name='technical_error_logs')
    op.drop_index(op.f('ix_technical_error_logs_occurred_at'), table_name='technical_error_logs')
    op.drop_index(op.f('ix_technical_error_logs_module'), table_name='technical_error_logs')
    op.drop_table('technical_error_logs')
    op.drop_table('strategy_definitions')
    op.drop_index(op.f('ix_service_health_events_service_name'), table_name='service_health_events')
    op.drop_table('service_health_events')
    op.drop_index(op.f('ix_assets_canonical_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
