"""execution_context_switches

Revision ID: 0003
Revises: 0002

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_context_switches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('from_context_id', sa.UUID(), nullable=True),
    sa.Column('to_context_id', sa.UUID(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('switched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_context_id'], ['execution_contexts.id'], name=op.f('fk_execution_context_switches_from_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['to_context_id'], ['execution_contexts.id'], name=op.f('fk_execution_context_switches_to_context_id_execution_contexts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_execution_context_switches_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_context_switches'))
    )
    op.create_index(op.f('ix_execution_context_switches_to_context_id'), 'execution_context_switches', ['to_context_id'], unique=False)
    op.create_index(op.f('ix_execution_context_switches_user_id'), 'execution_context_switches', ['user_id'], unique=False)
    # ### end Alembic commands ###

    op.create_check_constraint(
        op.f('ck_execution_contexts_kind'),
        'execution_contexts',
        "kind IN ('PAPER', 'REPLAY', 'DRY_RUN')",
    )

    op.execute('UPDATE execution_contexts SET is_active = false')
    op.create_index(
        'uq_execution_contexts_one_active_per_user',
        'execution_contexts',
        ['user_id'],
        unique=True,
        postgresql_where=sa.text('is_active'),
    )


def downgrade() -> None:
    op.drop_index('uq_execution_contexts_one_active_per_user', table_name='execution_contexts')
    op.drop_constraint(op.f('ck_execution_contexts_kind'), 'execution_contexts', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_context_switches_user_id'), table_name='execution_context_switches')
    op.drop_index(op.f('ix_execution_context_switches_to_context_id'), table_name='execution_context_switches')
    op.drop_table('execution_context_switches')
    # ### end Alembic commands ###
